name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt-get update && sudo apt-get -f install cppcheck clang-format
    - name: Build
      run: make
    - name: Test
      run: make test
